import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import { AuthProvider } from "@/context/AuthContext";
import { UserProvider } from "@/context/UserContext";
import { ClientProvider } from "@/context/ClientContext";
import { VehiculeProvider } from "@/context/VehiculeContext";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`{ ${poppins.variable} }`}>
        <AuthProvider>
          <UserProvider>
            <VehiculeProvider>
              <ClientProvider>{children}</ClientProvider>
            </VehiculeProvider>
          </UserProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
