openapi: 3.0.0
info:
  title: API de Autenticación
  description: API para la autenticación de usuarios (login, logout, recuperación y cambio de contraseña)
  version: 1.1.0
components:
  schemas:
    Auth:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          description: El correo electrónico del usuario
          example: "user@example.com"
        password:
          type: string
          description: La contraseña del usuario
          example: "12345678"
    PublicUser:
      type: object
      properties:
        name:
          type: string
          description: Nombre del usuario
          example: "John Doe"
        identification:
          type: string
          description: Identificación del usuario
          example: "12345678"
        email:
          type: string
          description: Correo electrónico del usuario
          example: "user@example.com"
        role:
          type: string
          description: Rol del usuario
          example: "seller"
    ForgetPasswordRequest:
      type: object
      required:
        - email
      properties:
        email:
          type: string
          description: El correo electrónico del usuario
          example: "user@example.com"
    ChangePasswordRequest:
      type: object
      required:
        - newPassword
        - confirmPassword
        - token
      properties:
        newPassword:
          type: string
          description: Nueva contraseña del usuario
          example: "newSecurePassword123"
        confirmPassword:
          type: string
          description: Confirmación de la nueva contraseña
          example: "newSecurePassword123"
        token:
          type: string
          description: Token de recuperación de contraseña
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
paths:
  /api/auth/login:
    post:
      summary: Autentica al usuario y devuelve un token de acceso
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Auth"
      responses:
        "200":
          description: Usuario autenticado exitosamente, se devuelve el token y los datos del usuario
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: "#/components/schemas/PublicUser"
        "400":
          description: Error en la autenticación
        "500":
          description: Error en el servidor

  /api/auth/verifyToken:
    post:
      summary: Verifica el token de acceso y devuelve los datos del usuario
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: Token de acceso
                  example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
      responses:
        "200":
          description: Token válido
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PublicUser"
        "400":
          description: Token inválido
        "500":
          description: Error en el servidor

  /api/auth/logout:
    post:
      summary: Cierra la sesión del usuario y elimina el token de acceso
      tags:
        - Auth
      responses:
        "200":
          description: Sesión cerrada exitosamente
        "500":
          description: Error en el servidor

  /api/auth/forget-password:
    post:
      summary: Envía un correo electrónico con un enlace para restablecer la contraseña
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ForgetPasswordRequest"
      responses:
        "200":
          description: Email enviado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Mensaje de éxito
                    example: "Se ha enviado el mail"
        "400":
          description: Error en el envío del correo
        "500":
          description: Error en el servidor

  /api/auth/change-password:
    post:
      summary: Cambia la contraseña del usuario utilizando un token
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChangePasswordRequest"
      responses:
        "200":
          description: Contraseña cambiada exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Mensaje de éxito
                    example: "Contraseña actualizada exitosamente"
        "400":
          description: Error en el cambio de contraseña
        "500":
          description: Error en el servidor
